// Security middleware for the GUI local backend.
//
// Addresses F-GUI-01 from the April 2026 security audit: the local backend
// at 127.0.0.1:8787 used to ship `access-control-allow-origin: *` with no
// Host validation and no CSRF token, letting any web page read identity
// material and drive mutating endpoints.
//
// This module:
//   - generates a 256-bit per-launch CSRF token and persists it to
//     ~/.ebp/gui-backend.token at mode 0600 (Unix) for in-process clients
//     (Tauri webview, email extension) to read.
//   - validates the Host header on every request (blocks DNS rebinding).
//   - validates the Origin header against an allow-list (blocks reading
//     responses cross-origin) and rejects early with 403 for requests
//     coming from unknown origins.
//   - requires `x-ebp-csrf: <token>` on every mutating (non-GET/HEAD)
//     request, using a constant-time comparison.

const DEFAULT_ALLOWED_HOSTS: ReadonlySet<string> = new Set([
	"127.0.0.1:8787",
	"localhost:8787",
]);

const DEFAULT_ALLOWED_ORIGINS: ReadonlySet<string> = new Set([
	// Tauri 1.x webview origins (platform-dependent).
	"tauri://localhost",
	"https://tauri.localhost",
	"http://tauri.localhost",
	// Same-origin fetches from the static-served frontend.
	"http://127.0.0.1:8787",
	"http://localhost:8787",
	"null",
]);

const CSRF_HEADER = "x-ebp-csrf";
const CSRF_EXEMPT_PATHS: ReadonlySet<string> = new Set([
	"/api/v1/health",
	"/api/v1/csrf-token",
	// OAuth provider redirects back to this GET endpoint with a state token
	// generated by the backend; it's a top-level navigation and has its own
	// per-launch random state protection.
	"/api/v1/mail/oauth/callback",
]);

let csrfToken: string | null = null;
let tokenPersistPath: string | null = null;
let extraAllowedOrigins: Set<string> = new Set();
let allowedHosts: Set<string> = new Set(DEFAULT_ALLOWED_HOSTS);

function bytesToHex(bytes: Uint8Array): string {
	let out = "";
	for (const b of bytes) out += b.toString(16).padStart(2, "0");
	return out;
}

export function generateCsrfToken(): string {
	const bytes = new Uint8Array(32);
	crypto.getRandomValues(bytes);
	return bytesToHex(bytes);
}

export interface InitSecurityOptions {
	home?: string;
	host?: string;
	port?: number;
	extensionOrigin?: string;
	persist?: boolean;
}

export async function initSecurity(opts: InitSecurityOptions = {}): Promise<string> {
	csrfToken = generateCsrfToken();
	extraAllowedOrigins = new Set();
	allowedHosts = new Set(DEFAULT_ALLOWED_HOSTS);
	tokenPersistPath = null;

	const envExt = opts.extensionOrigin ?? Deno.env.get("EBP_GUI_BACKEND_EXTENSION_ORIGIN");
	if (envExt) {
		for (const origin of envExt.split(",").map((s) => s.trim()).filter(Boolean)) {
			extraAllowedOrigins.add(origin);
		}
	}

	if (opts.host && opts.port !== undefined) {
		allowedHosts.add(`${opts.host}:${opts.port}`.toLowerCase());
	}

	const persist = opts.persist ?? true;
	if (persist) {
		const home = opts.home ?? Deno.env.get("HOME") ?? Deno.env.get("USERPROFILE") ?? "";
		if (home) {
			const ebpDir = `${home}/.ebp`;
			try {
				await Deno.mkdir(ebpDir, { recursive: true, mode: 0o700 });
			} catch (e) {
				if (!(e instanceof Deno.errors.AlreadyExists)) throw e;
			}
			tokenPersistPath = `${ebpDir}/gui-backend.token`;
			await Deno.writeTextFile(tokenPersistPath, csrfToken, { mode: 0o600 });
			if (Deno.build.os !== "windows") {
				try { await Deno.chmod(tokenPersistPath, 0o600); } catch { /* best-effort */ }
				try { await Deno.chmod(ebpDir, 0o700); } catch { /* best-effort */ }
			}
		}
	}

	return csrfToken;
}

export function setCsrfTokenForTest(token: string): void {
	csrfToken = token;
}

export function getCsrfToken(): string {
	if (!csrfToken) throw new Error("security not initialized: call initSecurity() first");
	return csrfToken;
}

export function getTokenPersistPath(): string | null {
	return tokenPersistPath;
}

function constantTimeEqual(a: string, b: string): boolean {
	if (a.length !== b.length) return false;
	let diff = 0;
	for (let i = 0; i < a.length; i += 1) {
		diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
	}
	return diff === 0;
}

export function isAllowedHost(host: string | null): boolean {
	if (!host) return false;
	return allowedHosts.has(host.toLowerCase());
}

export function isAllowedOrigin(origin: string | null): boolean {
	if (origin === null) return true;
	if (DEFAULT_ALLOWED_ORIGINS.has(origin)) return true;
	if (extraAllowedOrigins.has(origin)) return true;
	return false;
}

function errorResponse(status: number, message: string): Response {
	return new Response(JSON.stringify({ error: message }), {
		status,
		headers: { "content-type": "application/json" },
	});
}

export function validateSecurity(req: Request): Response | null {
	if (!isAllowedHost(req.headers.get("host"))) {
		return errorResponse(403, "host not allowed");
	}

	const origin = req.headers.get("origin");
	if (origin !== null && !isAllowedOrigin(origin)) {
		return errorResponse(403, "origin not allowed");
	}

	if (req.method === "OPTIONS" || req.method === "GET" || req.method === "HEAD") {
		return null;
	}

	const pathname = safePathname(req.url);
	if (pathname && CSRF_EXEMPT_PATHS.has(pathname)) return null;

	const provided = req.headers.get(CSRF_HEADER);
	if (!provided) return errorResponse(403, "csrf token required");
	if (!csrfToken) return errorResponse(403, "csrf not initialized");
	if (!constantTimeEqual(provided, csrfToken)) return errorResponse(403, "csrf token invalid");

	return null;
}

function safePathname(reqUrl: string): string | null {
	try {
		return new URL(reqUrl).pathname;
	} catch {
		return null;
	}
}

export function applyCorsHeaders(req: Request, res: Response): Response {
	const origin = req.headers.get("origin");
	const headers = new Headers(res.headers);
	if (origin && isAllowedOrigin(origin)) {
		headers.set("access-control-allow-origin", origin);
		headers.set("access-control-allow-credentials", "true");
		const prevVary = headers.get("vary");
		headers.set("vary", prevVary ? `${prevVary}, origin` : "origin");
	}
	headers.set("access-control-allow-headers", `content-type, ${CSRF_HEADER}`);
	headers.set("access-control-allow-methods", "GET,POST,OPTIONS");
	return new Response(res.body, {
		status: res.status,
		statusText: res.statusText,
		headers,
	});
}

export const CSRF_HEADER_NAME = CSRF_HEADER;
